export const SAGA_INSTRUMENT_LIST = 'SAGA_INSTRUMENT_LIST'
export const SAGA_INSTRUMENT_SELECT = 'SAGA_INSTRUMENT_SELECT'

export const FETCH_INSTRUMENT_LIST = 'FETCH_INSTRUMENT_LIST'
export const FETCH_CURRENT_INSTRUMENT = 'FETCH_CURRENT_INSTRUMENT'