export const SAGA_MACRO_PARAMETER_LIST = 'SAGA_MACRO_PARAMETER_LIST'
export const SAGA_EDIT_MACRO_PARAMETER = 'SAGA_EDIT_MACRO_PARAMETER'

export const FETCH_MACRO_PARAMETER_LIST = 'FETCH_MACRO_PARAMETER_LIST'
export const FETCH_CURRENT_MACRO_PARAMETER = 'FETCH_CURRENT_MACRO_PARAMETER'

export const SHOW_EDIT_MACRO_PARAMETER_MODAL = 'SHOW_EDIT_MACRO_PARAMETER_MODAL'
export const HIDE_EDIT_MACRO_PARAMETER_MODAL = 'HIDE_EDIT_MACRO_PARAMETER_MODAL'
