export const SAGA_PORTFOLIO_POSITION_LIST = 'SAGA_PORTFOLIO_POSITION_LIST'
export const SAGA_EDIT_PORTFOLIO_POSITION = 'SAGA_EDIT_PORTFOLIO_POSITION'
export const SAGA_EDIT_PORTFOLIO_TOTAL_SUM = 'SAGA_EDIT_PORTFOLIO_TOTAL_SUM'

export const FETCH_PORTFOLIO_POSITION_LIST = 'FETCH_PORTFOLIO_POSITION_LIST'
export const FETCH_CURRENT_PORTFOLIO_POSITION = 'FETCH_CURRENT_PORTFOLIO_POSITION'
export const FETCH_PORTFOLIO_TOTAL_SUM = 'FETCH_PORTFOLIO_TOTAL_SUM'

export const SHOW_EDIT_PORTFOLIO_POSITION_MODAL = 'SHOW_EDIT_PORTFOLIO_POSITION_MODAL'
export const HIDE_EDIT_PORTFOLIO_POSITION_MODAL = 'HIDE_EDIT_PORTFOLIO_POSITION_MODAL'

export const SHOW_EDIT_PORTFOLIO_TOTAL_SUM_MODAL = 'SHOW_EDIT_PORTFOLIO_TOTAL_SUM_MODAL'
export const HIDE_EDIT_PORTFOLIO_TOTAL_SUM_MODAL = 'HIDE_EDIT_PORTFOLIO_TOTAL_SUM_MODAL'
